# Generated by Django 6.0 on 2026-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='address',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
    ]
